baseURL = 'https://10douaris.top/'
languageCode = 'zh-cn'
title = 'aristendou的测试博客'
theme = 'stack'

[params]
  mainSections = ["posts"]

[params.sidebar]
  subtitle = "欢迎来到我的网站"

[params.article]
  math = false
  toc = true

[[menu.main]]
  name = "下载中心"
  url = "https://download.10douaris.top/"